version: '3.8'
services:
  dev-database:
    image: postgres:latest
    container_name: dev-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ninh1337
      POSTGRES_DB: dev
    restart: always
    volumes:
      - my-dbdata:/var/lib/postgresql/data
    networks:
      - nestjs-networks

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - nestjs-networks

networks:
  nestjs-networks:

volumes:
  my-dbdata:
